Description: >
    This template deploys an EFS volume to the provide persistent store for
    containers running within an ECS cluster.

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    Subnets:
        Description: "Comma delimited string of Subnets to span the EFS across"
        Type: String

    SecurityGroup:
        Description: Default security group to initialize the MountTarget with
        Type: String

    ClusterName:
        Description: A name to use to identify the ECS cluster this EFS volume supports
        Type: String

Resources:
    FileSystem:
        Type: AWS::EFS::FileSystem
        Properties:
            PerformanceMode: generalPurpose
            FileSystemTags:
            -
                Key: Name
                Value: !Sub "${EnvironmentName}-EFS"

    MountTarget0:
        Type: AWS::EFS::MountTarget
        Properties:
            FileSystemId: !Ref FileSystem
            SubnetId: !Select [0, !Split [",", !Ref Subnets]]
            SecurityGroups:
            - !Ref SecurityGroup

    MountTarget1:
        Type: AWS::EFS::MountTarget
        Properties:
            FileSystemId: !Ref FileSystem
            SubnetId: !Select [1, !Split [",", !Ref Subnets]]
            SecurityGroups:
            - !Ref SecurityGroup

Outputs:
    MountTarget0Id:
        Description: Mount target ID
        Value: !Ref MountTarget0

    MountTarget1Id:
        Description: Mount target ID
        Value: !Ref MountTarget1

    FileSystemId:
        Description: File system ID
        Value: !Ref FileSystem
        Export:
            Name: !Sub "${EnvironmentName}-EFS-${ClusterName}"