Description: >

    This template deploys a VPC, with a pair of public and private subnets spread
    across two Availabilty Zones. It deploys an Internet Gateway, with a default
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
    and default routes for them in the private subnets.

    It then deploys a highly available ECS cluster using an AutoScaling Group, with
    ECS hosts distributed across multiple Availability Zones.

    Finally, it deploys a pair of example ECS services from containers published in
    Amazon EC2 Container Registry (Amazon ECR).

Parameters:

    # Global
    EnvironmentName:
        Type: String

    TemplateBucket:
        Description: Bucket location of CF Templates
        Type: String

    # VPC 
    VpcCIDR:
        Description: VPC based network CIDR allocation
        Type: String

    PublicSubnets:
        Description: Choose which public subnets the VPC contains (holds NAT gateways)
        Type: String

    PrivateSubnets:
        Description: Choose which private subnets the VPC contains (holds services)
        Type: String

    # ECS
    InstanceType:
        Description: Instance type used for ECS hosts
        Type: String

    KeyName:
        Description: Key pair name for ssh access
        Type: String

    MinClusterSize:
        Description: How many ECS hosts do you want to initially deploy?
        Type: Number

    MaxClusterSize:
        Description: Maximum number of ECS hosts to deploy
        Type: Number
    
    DesiredClusterSize:
        Description: Desired number of ECS hosts for initial deploy
        Type: Number

    # BastionHost
    BastionHostKeyName:
        Description: Key used for SSH access to bastion host
        Type: String

Resources:
    Infra:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ["", [ "https://s3.amazonaws.com/", !Ref TemplateBucket, "/infrastructure/init.yaml" ] ]
            Parameters:
                EnvironmentName: !Ref EnvironmentName
                TemplateBucket: !Ref TemplateBucket
                VpcCIDR: !Ref VpcCIDR
                PublicSubnets: !Ref PublicSubnets
                PrivateSubnets: !Ref PrivateSubnets
                BastionHostKeyName: !Ref BastionHostKeyName
    ECS:
        Type: AWS::CloudFormation::Stack
        DependsOn:
        - Infra
        Properties:
            TemplateURL: !Join ["", [ "https://s3.amazonaws.com/", !Ref TemplateBucket, "/ecs/init.yaml" ] ]
            Parameters:
                EnvironmentName: !Ref EnvironmentName
                TemplateBucket: !Ref TemplateBucket
                KeyName: !Ref KeyName
                InstanceType: !Ref InstanceType
                MinClusterSize: !Ref MinClusterSize
                MaxClusterSize: !Ref MaxClusterSize
                DesiredClusterSize: !Ref DesiredClusterSize

    Services:
        Type: AWS::CloudFormation::Stack
        DependsOn: ECS
        Properties:
            TemplateURL: !Join ["", [ "https://s3.amazonaws.com/", !Ref TemplateBucket, "/services/init.yaml" ] ]
            Parameters:
                EnvironmentName: !Ref EnvironmentName
                TemplateBucket: !Ref TemplateBucket
    
